
access_key: AA
secret_key: BB

email:
  enabled: false
  host: smtp.gmail.com
  port: 587
  tls: true
  user: someone@somewhere.se
  password: secret


debug: false
ptp:
  downloadModels: true
  replicaCount: 1

  image:
    repository: ghcr.io/pharmbio/ptp
    tag: develop
    pullPolicy: Always

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ptp.pharmb.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  existingClaim: "ptp-models"
  secretName: "ptp-models-secret"
#  accessMode: ReadWriteMany
#  size: 1Gi
#  storageClass: ""