apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ptp-media-dir
  name: ptp-media-dir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
