apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ptp-worker-claim0
  name: ptp-worker-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
