apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ptp-models-volume
  name: ptp-models-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
