apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ptp-worker
  name: ptp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ptp-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ptp-worker
    spec:
      initContainers:
      - name: init-git-cloner
        image: alpine/git:latest
        volumeMounts:
          - name: ptp-worker-claim0
            mountPath: /models
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            git clone https://huggingface.co/pharmbio/ptp /models && \
            cd /models && \
            git lfs pull
      containers:
        - args:
            - celery
            - -A
            - ptp.celery
            - worker
            - --loglevel=info
            - --concurrency=8
          env:
            - name: CELERY_BROKER_URL
              value: redis://ptp-redis:6379/0
            - name: DATABASE_URL
              value: postgres://postgres:postgres@ptp-db:5432/postgres
            - name: GET_HOSTS_FROM
              value: dns
            - name: REDIS_URL
              value: redis://ptp-redis:6379/0
          image: {{ .Values.ptp.image.repository }}:{{ .Values.ptp.image.tag }}
          name: worker
          volumeMounts:
            - mountPath: /app/inference/models/
              name: ptp-worker-claim0
      restartPolicy: Always
      volumes:
        - name: ptp-worker-claim0
          persistentVolumeClaim:
            claimName: ptp-worker-claim0
