apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ptp-{{ .Release.Name }}
  name: ptp-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ptp-{{ .Release.Name }}

  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ptp-{{ .Release.Name }}
    spec:
      initContainers:
        {{- if not .Values.postgres }}
        - name: wait-for-db
          #image: postgres
          image: postgres
          #command: [ 'sh', '-c', 'until pg_isready --host=centauradb-{{ .Release.Name }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local --port=5432; do echo waiting for database; sleep 2; done;' ]
          command: [ 'sh', '-c', 'until pg_isready --host=ptp-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local --port=5432; do echo waiting for database; sleep 2; done;' ]
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
        {{- end }}
      containers:
        - args:
            - sh
            - -c
            - /app/run.sh
          env:
          {{- if .Values.debug }}
          - name: DEBUG
            value: "true"
          {{- end }}

          image: {{ .Values.ptp.image.repository }}:{{ .Values.ptp.image.tag }}

          name: ptp-{{ .Release.Name }}
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: settings-volume
              mountPath: /app/ptp/settings.py
              subPath: settings.py
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: settings-volume
          configMap:
            name: settings-config-{{ .Release.Name }}